title: Scientific Project Template
description: This page is a template for scientific project pages

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
