title: LabDAO Project Template
description: This page is a template for scientific project pages

# Build settings
show_downloads: false
show_heilmeier_catechism: true
markdown: kramdown
remote_theme: labdao/project-theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
